### ISSUE TITLE
seal-20000数据

### ISSUE THREAD

**Issue by nicheng0019** [liuyifan6613/DocBank-Document-Enhancement-Dataset#2]
请问seal-20000 中某些印章数据是做了模糊处理吗？

**Comment by liuyifan6613** [comment]
是的，有部分加了随机噪声和模糊。

**Comment by nicheng0019** [comment]
对应的gt文件是不是没有加模糊？这样图像和gt文件是不是对应不上了？

**Comment by liuyifan6613** [comment]
是的，但是不会有很大的影响，最初的目的就是增加鲁棒性，因为事实上很多场景下不可能和gt做到完全对应的，其他的数据都用上的话这部分的比例就不多。

**Comment by nicheng0019** [comment]
好的，谢谢
